[project]
id = "jkutner/pycraft"
name = "Minecraft with Python"
version = "1.0.0"

[build]
exclude = [ 
    ".env", 
    ".terraform", 
    "world", 
    "config" 
]

[[build.env]]
name='MINECRAFT_VERSION'
value="1.12.2"

[[build.env]]
name='MINECRAFT_DIST'
value="spigot"
