name: Publish
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - '*.yml'
    - '*.txt'
    - '*.properties'
    - 'makefile'
    - 'project.toml'

jobs:
    create-package:
        name: Publish Image
        runs-on:
            - ubuntu-latest
        steps:
            - id: checkout
              name: Checkout code
              uses: actions/checkout@v2
            - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
              name: Login to GitHub Package Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GHCR_TOKEN }}
            - id: setup-pack
              name: Install Pack
              uses: buildpacks/github-actions/setup-pack@v3.1.0
            - id: build
              name: Build & Publish
              run: |
                touch .env
                make publish
              shell: bash
              env:
                IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/apps/pycraft
